apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose/docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: cart-service
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cart-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose/docker-compose.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: cart-service
    spec:
      containers:
        - env:
            - name: AUTH_HOST
              value: auth-service
            - name: AUTH_PORT
              value: "50050"
            - name: CART_HOST
              value: cart-service
            - name: CART_HTTP_PORT
              value: "8083"
            - name: CART_PORT
              value: "50053"
            - name: HOST
              value: 0.0.0.0
            - name: LOG_LEVEL
              value: info
            - name: PRODUCT_HOST
              value: product-service
            - name: PRODUCT_PORT
              value: "50052"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_NUMBER
              value: "0"
            - name: REDIS_PASSWORD
            - name: REDIS_PORT
              value: "6379"
            - name: USER_HOST
              value: user-service
            - name: USER_PORT
              value: "50051"
          image: cart-service:latest
          imagePullPolicy: Never
          name: cart-service
          ports:
            - containerPort: 50053
              protocol: TCP
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
