apiVersion: v1
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:8081']

      - job_name: 'product-service'
        static_configs:
          - targets: ['product-service:8082']

      - job_name: 'cart-service'
        static_configs:
          - targets: ['cart-service:8083']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
