version: '3.9'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - .env
    depends_on:
      - user-service
      - product-service
      - cart-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "${USER_PORT}:${USER_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"
    env_file:
      - .env
    depends_on:
      - mongo

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    container_name: cart-service
    ports:
      - "${CART_PORT}:${CART_PORT}"
    env_file:
      - .env
    depends_on:
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "${USER_DB_PORT}:${USER_DB_PORT}"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  redis-data:
  mongo-data:
