version: '3.9'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - user-service
      - product-service
      - cart-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - user-db

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "50052:50052"
    env_file:
      - .env
    depends_on:
      - mongo

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    container_name: cart-service
    ports:
      - "50053:50053"
    env_file:
      - .env
    depends_on:
      - redis

  user-db:
    image: postgres:15
    container_name: user-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - user-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

volumes:
  user-db-data:
  redis-data:
  mongo-data:
