name: golangci-lint

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install golangci-lint
        run: |
          wget https://github.com/golangci/golangci-lint/releases/download/v1.60.3/golangci-lint-1.60.3-linux-amd64.tar.gz
          tar -xvzf golangci-lint-1.60.3-linux-amd64.tar.gz
          sudo mv golangci-lint-1.60.3-linux-amd64/golangci-lint /usr/local/bin/
          
      - name: Run golangci-lint for all services
        run: |
          for dir in $(find . -name "go.mod" -exec dirname {} \;); do
            echo "Running golangci-lint in $dir"
            (cd "$dir" && go mod tidy && golangci-lint run -c ../.golangci.yml) || exit 1
          done
