name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: Lint All Services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Lint all services
        run: |
          if [ ! -f .golangci.yml ]; then
            echo "Configuration file .golangci.yml not found in the root directory."
            exit 1
          fi

          for dir in $(find . -name "go.mod" -exec dirname {} \;); do
            echo "Running golangci-lint in $dir"
            (cd "$dir" && golangci-lint run -c ../.golangci.yml)
          done
